### ISSUE TITLE
Failed to parse mod file for starlight

### ISSUE THREAD

**Issue by Broyojo** [Senth/minecraft-mod-manager#159] opened 2022-03-04 03:32 UTC
### Describe the bug 
I had installed starlight using this manager a while ago in 1.18.1, and now when I tried to update all my mods to 1.18.2, I got this error message:
```
Failed to parse mod file starlight-1.0.2+fabric.89b8d9f.jar
Traceback (most recent call last):
  File "/home/broyojo/.local/lib/python3.10/site-packages/minecraft_mod_manager/gateways/jar_parser.py", line 46, in _get_mod_info
    with ZipFile(file, "r") as zip:
  File "/usr/lib/python3.10/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.10/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

### Steps to reproduce
1. Ran `mmm install starlight -v 1.18.1` 
1. Ran `mmm update -v 1.18.2`

### Expected Behavior
I expected that starlight should be updated to 1.18.2.

### Info
 - OS: Arch Linux
 - Python --version: 3.10.2
 - minecraft-mod-manager --version: 1.2.6

**Comment by theofficialgman** [comment] 2022-03-06 04:27
its not starlight in particular
duplicate of https://github.com/Senth/minecraft-mod-manager/issues/150

**Comment by Senth** [comment] 2022-03-06 09:42
Looking into this issue (#150) now and hopefully, it will be fixed for real this time 🙂

**Closed by Senth** 2022-03-06 09:42 UTC
Labels: bug, duplicate
