### ISSUE TITLE
Automatic Mod Dependency Management

### ISSUE THREAD

**Issue by Broyojo** [Senth/minecraft-mod-manager#144] opened 2021-11-28 14:10 UTC
When I'm downloading mods, I have to go to the website for the mod and look at the all the dependencies and then manually install them, which is a pain. 

When downloading mods with this tool, it would be nice for it to automatically download and keep track of dependencies. 

I don't know other alternatives to this, but I guess we could find out how GDLauncher keeps track of mod dependencies.

Some mods that have some dependencies are tweakeroo, minihud, and litematica which all depend on malilib. A fair number of mods also rely on fabric-api.

**Comment by Senth** [comment] 2022-03-19 13:02
Duplicate of #26

Will add this in the next minor release (v1.3) 🙂

**Closed by Senth** 2022-03-19 13:02 UTC
Labels: duplicate, enhancement
