### ISSUE TITLE
Add support for recursive mod search

### ISSUE THREAD

**Issue by boerdereinar** [Senth/minecraft-mod-manager#133] opened 2021-10-27 17:34 UTC
### Is your feature request related to a problem? Please describe.
I use the thatorthis mod for fabric to organize my mod list and mod configurations. Currently I need to go to each folder to update my mods.

### Describe the solution you'd like
Add '-r' or '--recursive' as an cli argument which resursively searches the current directory and all its subdirectories.

**Comment by Senth** [comment] 2021-10-31 13:13
A similar feature to this is planned for v2 of this application 🙂 

Basically, the application (including GUI) will know all the mod locations meaning you won't have to specify a directory and it's a one-click/command to update all mods everywhere 🙂 (also keeping track to not upgrade to a wrong MC version).

Duplicate of #115

**Closed by Senth** 2021-10-31 13:13 UTC
Labels: duplicate, enhancement
