### ISSUE TITLE
Downloading via slug doesn't persist if mod name attribute varies

### ISSUE THREAD

**Issue by kjc75** [Senth/minecraft-mod-manager#32] opened 2021-04-27 20:06 UTC
For example, if you download unearthed-fabric, it will pull from curse, but store in the sqlite as simply unearthed, requiring a further ```configure unearthed=unearthed-fabric``` in order for an update to work in the future.

**Comment by Senth** [comment] 2021-04-28 21:20
Thanks for reporting 🙂

I forgot to implement this functionality when I rewrote the whole application. Not sure if the label "bug" or "enhancement" fits better since it's generally not a bug, but more of hidden functionality that you can download through a slug.

I will mark it as a bug though to give it a higher priority and it does "break" the application, making installation + update not work as expected. Might have some time to look into this during the weekend, but can't promise anything.

**Comment by Senth** [comment] 2021-04-29 18:19
Hmm, started looking into the problem and it requires some restructuring to fix. At least if I want a clean and modular solution. Will have to think a bit about how to best solve this without tightly coupling the code.

So probably won't be fixed this weekend.

**Closed** 2021-07-03 00:25 UTC
Labels: bug, refactor

**Comment by Senth** [comment] 2021-07-03 00:26
I will include this in the next update during this weekend 🙂
