### ISSUE TITLE
Fabric-api duplication on new version release

### ISSUE THREAD

**Issue by theofficialgman** [Senth/minecraft-mod-manager#132] opened 2021-10-22 22:27 UTC
### Describe the bug 
When running `minecraft-mod-manager -v "1.17.1 --beta --alpha install fabric-api`, a new version of fabric-api keeps getting added whenever a new version is released instead of removing the old version and downloading the new version

### Steps to reproduce
1. ran `minecraft-mod-manager -v "1.17.1 --beta --alpha install fabric-api`
2. wait for new version of fabric-api to be released and then ran `minecraft-mod-manager -v "1.17.1 --beta --alpha install fabric-api`
3. two versions of fabric-api are then downloaded and installed

### Expected Behavior
the old version of fabric-api is removed and only the new version remains

### Info
 - OS: Ubuntu Bionic 18.04
 - Python --version: 3.6.9
 - minecraft-mod-manager --version: 1.04

**Comment by Senth** [comment] 2021-10-31 14:26
Hi theofficialgman,

It seems you're running an old version of `minecraft-mod-manager`. This issue was fixed in #54.

The latest version is `1.2.4` and unfortunately, requires at least python `3.8` to be able to install/upgrade. I think that might be the cause why you've downloaded an old version of `minecraft-mod-manager`.

**Closed by Senth** 2021-10-31 14:26 UTC
Labels: bug, invalid

**Comment by theofficialgman** [comment] 2021-10-31 21:39
ah thank you I didn't notice that.
I was installing with `python3.8 -m pip install --upgrade minecraft-mod-manager` and for some reason it was stuck on `1.0.4` and would not upgrade
Uninstalling and reinstalling fixed and now I have `1.2.5`
